=== Juliiscoding/latestAI/etl/validators/schemas/category.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Category Schema",
  "description": "Schema for validating category data from ProHandel API",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "description": "Unique identifier for the category"
    },
    "number": {
      "type": ["number", "string", "null"],
      "description": "Category number"
    },
    "name": {
      "type": ["string", "null"],
      "description": "Name of the category"
    },
    "searchTerm": {
      "type": ["string", "null"],
      "description": "Search term for the category"
    },
    "departmentNumber": {
      "type": ["number", "string", "null"],
      "description": "Department number"
    },
    "labelNumber": {
      "type": ["number", "string", "null"],
      "description": "Label number"
    },
    "mainDepartmentNumber": {
      "type": ["number", "string", "null"],
      "description": "Main department number"
    },
    "mainCategoryNumber": {
      "type": ["number", "string", "null"],
      "description": "Main category number"
    },
    "generalCategoryNumber": {
      "type": ["number", "string", "null"],
      "description": "General category number"
    },
    "taxNumber": {
      "type": ["number", "string", "null"],
      "description": "Tax number"
    },
    "isServiceCategory": {
      "type": ["boolean", "null"],
      "description": "Whether it's a service category"
    },
    "lastChange": {
      "type": ["string", "null"],
      "format": "date-time",
      "description": "Last change timestamp of the category"
    },
    "isDeleted": {
      "type": ["boolean", "null"],
      "description": "Whether the category is deleted"
    }
  },
  "required": ["id"],
  "additionalProperties": true
}

=== Juliiscoding/latestAI/data/category.json
[
  {
    "departmentNumber": 3,
    "labelNumber": 1,
    "mainDepartmentNumber": 0,
    "mainCategoryNumber": 10,
    "generalCategoryNumber": 100,
    "taxNumber": 1,
    "name": "Bettw\u00e4sche Mikrofaser",
    "isServiceCategory": false,
    "id": "a81fc591-551c-454b-ae6f-f357bfc8784c",
    "searchTerm": "Bettw\u00e4sche Mikr",
    "number": 1010,
    "lastChange": "2019-10-22T17:51:56.6267566",
    "isDeleted": false
  },
  {
    "departmentNumber": 3,
    "labelNumber": 1,
    "mainDepartmentNumber": 0,
    "mainCategoryNumber": 10,
    "generalCategoryNumber": 100,
    "taxNumber": 1,
    "name": "Bettw\u00e4sche Renforce",
    "isServiceCategory": false,
    "id": "02e5e487-c88a-49fa-9144-cb9dcd6e5ba5",
    "searchTerm": "Bettw\u00e4sche Renf",
    "number": 1011,
    "lastChange": "2019-10-22T17:51:56.6267566",
    "isDeleted": false
  },
  {
    "departmentNumber": 3,
    "labelNumber": 1,
    "mainDepartmentNumber": 0,
    "mainCategoryNumber": 10,
    "generalCategoryNumber": 100,
    "taxNumber": 1,
    "name": "Bettw\u00e4sche Satin",
    "isServiceCategory": false,
    "id": "e301dcbd-9d8a-4727-97dc-cdfd67bacfef",
    "searchTerm": "Bettw\u00e4sche Sati",
    "number": 1012,
    "lastChange": "2019-10-22T17:51:56.6267566",
    "isDeleted": false
  },
  {
    "departmentNumber": 3,
    "labelNumber": 1,
    "mainDepartmentNumber": 0,
    "mainCategoryNumber": 10,
    "generalCategoryNumber": 100,
    "taxNumber": 1,
    "name": "Bettw\u00e4sche Jersey",
    "isServiceCategory": false,
    "id": "598cce27-d348-47e1-8e7d-000bd81da717",
    "searchTerm": "Bettw\u00e4sche Jers",
    "number": 1013,
    "lastChange": "2019-10-22T17:51:56.6267566",
    "isDeleted": false
  },
  {
    "departmentNumber": 3,
    "labelNumber": 1,
    "mainDepartmentNumber": 0,
    "mainCategoryNumber": 10,
    "generalCategoryNumber": 100,
    "taxNumber": 1,
    "name": "Bettw Flanell/Frottee",
    "isServiceCategory": false,
    "id": "62165220-f835-47c8-956e-49f610d46605",
    "searchTerm": "Bettw Flanell/F",
    "number": 1014,
    "lastChange": "2019-10-22T17:51:56.6267566",
    "isDeleted": false
  },
  {
    "departmentNumber": 3,
    "labelNumber": 1,
    "mainDepartmentNumber": 0,
    "mainCategoryNumber": 10,
    "generalCategoryNumber": 100,
    "taxNumber": 1,
    "name": "Kinderbettw\u00e4sche",
    "isServiceCategory": false,
    "id": "dce1581b-5d56-48a0-bd40-a870efe17fc4",
    "searchTerm": "Kinderbettw\u00e4sch",
    "number": 1015,
    "lastChange": "2019-10-22T17:51:56.6267566",
    "isDeleted": false
  },
  {
    "departmentNumber": 3,
    "labelNumber": 1,
    "mainDepartmentNumber": 0,
    "mainCategoryNumber": 10,
    "generalCategoryNumber": 100,
    "taxNumber": 1,
    "name": "Reparaturen",
    "isServiceCategory": true,
    "id": "03050591-820b-4d6b-bc04-dd861f07776c",
    "searchTerm": "Reparaturen",
    "number": 1017,
    "lastChange": "2019-10-22T17:51:56.6267566",
    "isDeleted": false
  },
  {
    "departmentNumber": 3,
    "labelNumber": 1,
    "mainDepartmentNumber": 0,
    "mainCategoryNumber": 10,
    "generalCategoryNumber": 100,
    "taxNumber": 1,
    "name": "Kissenbez\u00fcge",
    "isServiceCategory": false,
    "id": "0179d547-f54d-4816-a772-16f2726fd18b",
    "searchTerm": "Kissenbez\u00fcge",
    "number": 1020,
    "lastChange": "2019-10-22T17:51:56.6267566",
    "isDeleted": false
  },
  {
    "departmentNumber": 3,
    "labelNumber": 1,
    "mainDepartmentNumber": 0,
    "mainCategoryNumber": 10,
    "generalCategoryNumber": 100,
    "taxNumber": 1,
    "name": "Accessoires",
    "isServiceCategory": false,
    "id": "9f19953e-f6b5-40f6-baf1-de2ae40526eb",
    "searchTerm": "Accessoires",
    "number": 1031,
    "lastChange": "2019-10-22T17:51:56.6267566",
    "isDeleted": false
  },
  {
    "departmentNumber": 3,
    "labelNumber": 1,
    "mainDepartmentNumber": 0,
    "mainCategoryNumber": 10,
    "generalCategoryNumber": 100,
    "taxNumber": 2,
    "name": "Accessoires 7% MWSt",
    "isServiceCategory": false,
    "id": "9834ffd5-68a7-4615-b2ab-81ba14de5983",
    "searchTerm": "Accessoires 7%",
    "number": 1032,
    "lastChange": "2019-10-22T17:51:56.6267566",
    "isDeleted": false
  },
  {
    "departmentNumber": 3,
    "labelNumber": 1,
    "mainDepartmentNumber": 0,
    "mainCategoryNumber": 10,
    "generalCategoryNumber": 100,
    "taxNumber": 1,
    "name": "Spannlaken/offene Laken",
    "isServiceCategory": false,
    "id": "90cdd6c1-8a68-4f5b-b704-1cb1c7ecbbe5",
    "searchTerm": "Spannlaken/offe",
    "number": 1050,
    "lastChange": "2019-10-22T17:51:56.6267566",
    "isDeleted": false
  },
  {
    "departmentNumber": 3,
    "labelNumber": 1,
    "mainDepartmentNumber": 0,
    "mainCategoryNumber": 10,
    "generalCategoryNumber": 100,
    "taxNumber": 1,
    "name": "KATAG",
    "isServiceCategory": false,
    "id": "b82549ac-e104-4a36-95a5-79c33dd7222c",
    "searchTerm": "KATAG",
    "number": 1080,
    "lastChange": "2019-10-22T17:51:56.6267566",
    "isDeleted": false
  },
  {
    "departmentNumber": 3,
    "labelNumber": 99,
    "mainDepartmentNumber": 0,
    "mainCategoryNumber": 10,
    "generalCategoryNumber": 100,
    "taxNumber": 1,
    "name": "Eigenstickerei",
    "isServiceCategory": true,
    "id": "4a22f0a2-9729-4468-8e58-a515dab82a2d",
    "searchTerm": "Eigenstickerei",
    "number": 1097,
    "lastChange": "2019-10-22T17:51:56.6267566",
    "isDeleted": false
  },
  {
    "departmentNumber": 0,
    "labelNumber": 99,
    "mainDepartmentNumber": 0,
    "mainCategoryNumber": 0,
    "generalCategoryNumber": 0,
    "taxNumber": 1,
    "name": "Porto/Geb\u00fchren",
    "isServiceCategory": true,
    "id": "1a8fd22d-3d8e-4383-a697-ab15ea478c10",
    "searchTerm": "Porto/Geb\u00fchren",
    "number": 1100,
    "lastChange": "2019-10-22T17:51:56.6267566",
    "isDeleted": false
  },
  {
    "departmentNumber": 3,
    "labelNumber": 1,
    "mainDepartmentNumber": 0,
    "mainCategoryNumber": 12,
    "generalCategoryNumber": 120,
    "taxNumber": 1,
    "name": "HANDTUCH DAMAST/GERS",
    "isServiceCategory": false,
    "id": "217fa951-0e2d-4a58-a243-fe7a6a1a7fb7",
    "searchTerm": "HANDTUCH DAM",
    "number": 1200,
    "lastChange": "2019-10-22T17:51:56.6267566",
    "isDeleted": false
  },
  {
    "departmentNumber": 3,
    "labelNumber": 1,
    "mainDepartmentNumber": 0,
    "mainCategoryNumber": 12,
    "generalCategoryNumber": 120,
    "taxNumber": 1,
    "name": "Geschirr-/K\u00fcchent\u00fccher",
    "isServiceCategory": false,
    "id": "b51f6029-6a43-4d00-b9ce-12e0bd3ed5e8",
    "searchTerm": "Geschirr-/K\u00fcchent\u00fccher",
    "number": 1210,
    "lastChange": "2023-09-15T13:39:00.1759015",
    "isDeleted": false
  },
  {
    "departmentNumber": 3,
    "labelNumber": 1,
    "mainDepartmentNumber": 0,
    "mainCategoryNumber": 12,
    "generalCategoryNumber": 120,
    "taxNumber": 1,
    "name": "Eigenstickerei Lager",
    "isServiceCategory": false,
    "id": "fcf5a608-6d2a-4caf-b3ae-64ef5d063998",
    "searchTerm": "Eigenstickerei",
    "number": 1219,
    "lastChange": "2019-10-22T17:51:56.6267566",
    "isDeleted": false
  },
  {
    "departmentNumber": 3,
    "labelNumber": 1,
    "mainDepartmentNumber": 0,
    "mainCategoryNumber": 12,
    "generalCategoryNumber": 120,
    "taxNumber": 1,
    "name": "K\u00fcchenhandtuch Frottier",
    "isServiceCategory": false,
    "id": "8f280387-d05f-4941-a840-78a4f4801d3d",
    "searchTerm": "K\u00fcchenhandtuch",
    "number": 1220,
    "lastChange": "2019-10-22T17:51:56.6267566",
    "isDeleted": false
  },
  {
    "departmentNumber": 3,
    "labelNumber": 1,
    "mainDepartmentNumber": 0,
    "mainCategoryNumber": 12,
    "generalCategoryNumber": 120,
    "taxNumber": 1,
    "name": "Kalendert\u00fccher",
    "isServiceCategory": false,
    "id": "870d71c1-dd59-4c6d-9beb-9b9faab03db9",
    "searchTerm": "Kalendert\u00fccher",
    "number": 1230,
    "lastChange": "2019-10-22T17:51:56.6267566",
    "isDeleted": false
  },
  {
    "departmentNumber": 3,
    "labelNumber": 1,
    "mainDepartmentNumber": 0,
    "mainCategoryNumber": 12,
    "generalCategoryNumber": 120,
    "taxNumber": 1,
    "name": "Topfanfasser",
    "isServiceCategory": false,
    "id": "c5ac68d4-226e-4bcb-bee5-46304907a21b",
    "searchTerm": "Topfanfasser",
    "number": 1240,
    "lastChange": "2019-10-22T17:51:56.6267566",
    "isDeleted": false
  },
  {
    "departmentNumber": 3,
    "labelNumber": 1,
    "mainDepartmentNumber": 0,
    "mainCategoryNumber": 12,
    "generalCategoryNumber": 120,
    "taxNumber": 1,
    "name": "Sch\u00fcrzen",
    "isServiceCategory": false,
    "id": "0820a972-9c02-43e0-b929-15d086b770dd",
    "searchTerm": "Sch\u00fcrzen",
    "number": 1250,
    "lastChange": "2023-08-17T09:03:52.1103017",
    "isDeleted": false
  },
  {
    "departmentNumber": 3,
    "labelNumber": 1,
    "mainDepartmentNumber": 0,
    "mainCategoryNumber": 12,
    "generalCategoryNumber": 120,
    "taxNumber": 1,
    "name": "Accessoires",
    "isServiceCategory": false,
    "id": "eabc2370-df7e-4906-a620-99e02d991f30",
    "searchTerm": "Accessoires",
    "number": 1262,
    "lastChange": "2019-10-22T17:51:56.6267566",
    "isDeleted": false
  },
  {
    "departmentNumber": 3,
    "labelNumber": 1,
    "mainDepartmentNumber": 0,
    "mainCategoryNumber": 12,
    "generalCategoryNumber": 120,
    "taxNumber": 2,
    "name": "K\u00fcchenw\u00e4sche Geschenke 7%",
    "isServiceCategory": false,
    "id": "6af92210-8f0f-4a4a-ae9d-bf1fe4f8f067",
    "searchTerm": "K\u00fcchenw\u00e4sche Ge",
    "number": 1265,
    "lastChange": "2019-10-22T17:51:56.6267566",
    "isDeleted": false
  },
  {
    "departmentNumber": 3,
    "labelNumber": 1,
    "mainDepartmentNumber": 0,
    "mainCategoryNumber": 12,
    "generalCategoryNumber": 120,
    "taxNumber": 1,
    "name": "KATAG",
    "isServiceCategory": false,
    "id": "192308e8-5953-4d2c-9e71-f4f2cf842c9c",
    "searchTerm": "KATAG",
    "number": 1280,
