=== Juliiscoding/latestAI/etl/validators/schemas/supplier.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Supplier Schema",
  "description": "Schema for validating supplier data from ProHandel API",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "description": "Unique identifier for the supplier"
    },
    "number": {
      "type": ["number", "string", "null"],
      "description": "Supplier number"
    },
    "name1": {
      "type": ["string", "null"],
      "description": "Primary name of the supplier"
    },
    "name2": {
      "type": ["string", "null"],
      "description": "Secondary name of the supplier"
    },
    "name3": {
      "type": ["string", "null"],
      "description": "Tertiary name of the supplier"
    },
    "searchTerm": {
      "type": ["string", "null"],
      "description": "Search term for the supplier"
    },
    "street": {
      "type": ["string", "null"],
      "description": "Street address of the supplier"
    },
    "zipCode": {
      "type": ["string", "null"],
      "description": "Zip code of the supplier"
    },
    "city": {
      "type": ["string", "null"],
      "description": "City of the supplier"
    },
    "countryNumber": {
      "type": ["string", "null"],
      "description": "Country number of the supplier"
    },
    "telephone": {
      "type": ["string", "null"],
      "description": "Telephone number of the supplier"
    },
    "mobilePhone": {
      "type": ["string", "null"],
      "description": "Mobile phone number of the supplier"
    },
    "fax": {
      "type": ["string", "null"],
      "description": "Fax number of the supplier"
    },
    "email": {
      "type": ["string", "null"],
      "description": "Email address of the supplier"
    },
    "website": {
      "type": ["string", "null"],
      "description": "Website of the supplier"
    },
    "currencyNumber": {
      "type": ["string", "null"],
      "description": "Currency number of the supplier"
    },
    "isActive": {
      "type": ["boolean", "null"],
      "description": "Whether the supplier is active"
    },
    "isEDI": {
      "type": ["boolean", "null"],
      "description": "Whether the supplier uses EDI"
    },
    "bankCode": {
      "type": ["number", "string", "null"],
      "description": "Bank code of the supplier"
    },
    "bankAccount": {
      "type": ["string", "null"],
      "description": "Bank account of the supplier"
    },
    "iban": {
      "type": ["string", "null"],
      "description": "IBAN of the supplier"
    },
    "bic": {
      "type": ["string", "null"],
      "description": "BIC of the supplier"
    },
    "info1": {
      "type": ["string", "null"],
      "description": "Additional information 1"
    },
    "info2": {
      "type": ["string", "null"],
      "description": "Additional information 2"
    },
    "shipmentOptionNumber": {
      "type": ["number", "string", "null"],
      "description": "Shipment option number"
    },
    "paymentOptionNumber": {
      "type": ["number", "string", "null"],
      "description": "Payment option number"
    },
    "lastChange": {
      "type": ["string", "null"],
      "format": "date-time",
      "description": "Last change timestamp of the supplier"
    },
    "isDeleted": {
      "type": ["boolean", "null"],
      "description": "Whether the supplier is deleted"
    }
  },
  "required": ["id"],
  "additionalProperties": true
}

=== Juliiscoding/latestAI/data/supplier.json
[
  {
    "currencyNumber": "EUR",
    "countryNumber": "D",
    "isActive": false,
    "isEDI": false,
    "bankCode": 0,
    "email": "",
    "fax": "",
    "id": "91e50018-271b-35bb-a314-2da57cf325cc",
    "website": "",
    "iban": "",
    "info1": "",
    "info2": "",
    "bankAccount": "",
    "searchTerm": "",
    "mobilePhone": "",
    "name1": "Versandkosten Online",
    "name2": "",
    "name3": "",
    "number": 1,
    "city": "",
    "zipCode": "",
    "street": "",
    "bic": "",
    "telephone": "",
    "shipmentOptionNumber": 0,
    "paymentOptionNumber": 0,
    "lastChange": "2024-11-21T12:29:02.9941839",
    "isDeleted": false
  },
  {
    "currencyNumber": "EUR",
    "countryNumber": "D",
    "isActive": true,
    "isEDI": false,
    "bankCode": 37040044,
    "email": "info@abfash.com",
    "fax": "0221/27 05 98 10",
    "id": "b8f92432-57bc-4221-9ed9-bd05285fca52",
    "website": "",
    "iban": "",
    "info1": "",
    "info2": "",
    "bankAccount": "555543800",
    "searchTerm": "Abfash GmbH",
    "mobilePhone": "",
    "name1": "Abfash GmbH",
    "name2": "",
    "name3": "",
    "number": 10020,
    "city": "K\u00f6ln",
    "zipCode": "50672",
    "street": "Palmstr. 36",
    "bic": "",
    "telephone": "0049/221270598-0",
    "shipmentOptionNumber": 0,
    "paymentOptionNumber": 1,
    "lastChange": "2022-08-19T14:43:07.8438269",
    "isDeleted": false
  },
  {
    "currencyNumber": "EUR",
    "countryNumber": "D",
    "isActive": true,
    "isEDI": false,
    "bankCode": 76550000,
    "email": "info@accentra.de",
    "fax": "09822/828422",
    "id": "6541cc12-2b52-4efb-918e-615dd0eac181",
    "website": "www.accentra.de",
    "iban": "",
    "info1": "",
    "info2": "",
    "bankAccount": "430303073",
    "searchTerm": "Accentra GmbH",
    "mobilePhone": "",
    "name1": "Accentra GmbH & Co. KG",
    "name2": "",
    "name3": "Accentra",
    "number": 10057,
    "city": "Bechhofen",
    "zipCode": "91572",
    "street": "Rudolf-Diesel-Str. 7",
    "bic": "",
    "telephone": "09822/824840",
    "shipmentOptionNumber": 0,
    "paymentOptionNumber": 3,
    "lastChange": "2022-09-15T13:27:51.743932",
    "isDeleted": false
  },
  {
    "currencyNumber": "EUR",
    "countryNumber": "D",
    "isActive": true,
    "isEDI": false,
    "bankCode": 36010043,
    "email": "vorderstrase@hotmail.de",
    "fax": "",
    "id": "cb7e6d5f-b27b-0ebf-a414-fa1fc034f0bb",
    "website": "",
    "iban": "",
    "info1": "",
    "info2": "",
    "bankAccount": "293863439",
    "searchTerm": "Ma Re",
    "mobilePhone": "",
    "name1": "Agentur Ingo Vorderstrase",
    "name2": "MaRe",
    "name3": "",
    "number": 10070,
    "city": "Kempen",
    "zipCode": "47906",
    "street": "Rheinstr. 23 a",
    "bic": "",
    "telephone": "02845-37 76 30",
    "shipmentOptionNumber": 0,
    "paymentOptionNumber": 2,
    "lastChange": "2023-01-03T09:26:37.0624827",
    "isDeleted": false
  },
  {
    "currencyNumber": "EUR",
    "countryNumber": "D",
    "isActive": true,
    "isEDI": false,
    "bankCode": 21352240,
    "email": "unio@norbertgresch.de",
    "fax": "",
    "id": "cd53f41b-950a-b888-b414-6962886d04c2",
    "website": "",
    "iban": "",
    "info1": "",
    "info2": "",
    "bankAccount": "190015464",
    "searchTerm": "Unio Hamburg",
    "mobilePhone": "",
    "name1": "Agentur Norbert Gresch",
    "name2": "Unio Hamburg",
    "name3": "",
    "number": 10073,
    "city": "Hamburg",
    "zipCode": "22529",
    "street": "Offakamp 9a",
    "bic": "",
    "telephone": "+49 40/88 14 15 950",
    "shipmentOptionNumber": 0,
    "paymentOptionNumber": 3,
    "lastChange": "2023-09-21T09:00:31.2236696",
    "isDeleted": false
  },
  {
    "currencyNumber": "EUR",
    "countryNumber": "D",
    "isActive": true,
    "isEDI": false,
    "bankCode": 0,
    "email": "hello@1730.de",
    "fax": "040/4689762-8861",
    "id": "a6002195-eced-d1b2-5c14-014fd4c2d316",
    "website": "www.1730.de",
    "iban": "",
    "info1": "Zahlung: netto lt. Fa\u00dfbender\n",
    "info2": "",
    "bankAccount": "",
    "searchTerm": "Upleger",
    "mobilePhone": "",
    "name1": "Agentur Anna Upleger GmbH & Co. KG",
    "name2": "",
    "name3": "",
    "number": 10079,
    "city": "Hamburg",
    "zipCode": "22113",
    "street": "Grunsonstr. 55",
    "bic": "",
    "telephone": "040/4689762-70",
    "shipmentOptionNumber": 0,
    "paymentOptionNumber": 1,
    "lastChange": "2023-10-05T16:09:04.7990773",
    "isDeleted": false
  },
  {
    "currencyNumber": "EUR",
    "countryNumber": "D",
    "isActive": true,
    "isEDI": false,
    "bankCode": 0,
    "email": "",
    "fax": "08341-9610712",
    "id": "75bc4b1c-5c7f-4f83-b67d-b3d7aa1c3b5f",
    "website": "anton-huebner@t-online.de",
    "iban": "",
    "info1": "",
    "info2": "",
    "bankAccount": "",
    "searchTerm": "AHschmuckdesign",
    "mobilePhone": "",
    "name1": "AHschmuckdesign e. Kfr.",
    "name2": "Inh. Heidi H\u00fcbner",
    "name3": "",
    "number": 10080,
    "city": "Kaufbeuren",
    "zipCode": "87600",
    "street": "Buchenweg 24",
    "bic": "",
    "telephone": "08341-62235",
    "shipmentOptionNumber": 0,
    "paymentOptionNumber": 1,
    "lastChange": "2022-08-19T14:43:07.8438269",
    "isDeleted": false
  },
  {
    "currencyNumber": "EUR",
    "countryNumber": "E",
    "isActive": true,
    "isEDI": false,
    "bankCode": 0,
    "email": "ysabelmora@ysabelmora.com",
    "fax": "",
    "id": "b1aaba04-131f-52b6-a914-a88414683c03",
    "website": "www.ysabelmora.com",
    "iban": "",
    "info1": "",
    "info2": "",
    "bankAccount": "",
    "searchTerm": "Ysabel Mora",
    "mobilePhone": "",
    "name1": "AIMSA GRUPO TEXTIL S.L.",
    "name2": "Ysabel Mora",
    "name3": "Ysabel Mora",
    "number": 10085,
    "city": "Val\u00e8ncia",
    "zipCode": "46800",
    "street": "Calle Ronda Sequia de Meses, 3 X\u00e0tiva",
    "bic": "",
    "telephone": "+35 962-243 217",
    "shipmentOptionNumber": 0,
    "paymentOptionNumber": 15,
    "lastChange": "2023-09-20T14:54:14.5532566",
    "isDeleted": false
  },
  {
    "currencyNumber": "EUR",
    "countryNumber": "D",
    "isActive": true,
    "isEDI": false,
    "bankCode": 0,
    "email": "",
    "fax": "07432/90714-29",
    "id": "a06c629c-1aa7-4cba-8469-1f0c9f50e613",
    "website": "",
    "iban": "",
    "info1": "",
    "info2": "",
    "bankAccount": "",
    "searchTerm": "AlberGustav",
    "mobilePhone": "",
    "name1": "Gustav Alber",
    "name2": "",
    "name3": "",
    "number": 10096,
    "city": "Albstadt-Onstmettingen",
    "zipCode": "72461",
    "street": "J\u00e4gerstr.22",
    "bic": "",
    "telephone": "07432/90714-0",
    "shipmentOptionNumber": 0,
    "paymentOptionNumber": 7,
    "lastChange": "2022-08-19T14:43:07.8438269",
    "isDeleted": false
  },
  {
    "currencyNumber": "EUR",
    "countryNumber": "D",
    "isActive": true,
    "isEDI": false,
    "bankCode": 65050110,
    "email": "sales@albert-textil.de",
    "fax": "07506/234164",
    "id": "a5d455f4-2654-44cc-bea8-9261b2fdf434",
    "website": "",
    "iban": "",
    "info1": "",
    "info2": "",
    "bankAccount": "101113281",
    "searchTerm": "Albert Textil",
    "mobilePhone": "",
    "name1": "Albert Textil UG",
    "name2": "",
    "name3": "",
    "number": 10100,
    "city": "Wangen im Allg\u00e4u",
    "zipCode": "88239",
    "street": "Seestr.2",
    "bic": "",
    "telephone": "07506/5396739",
    "shipmentOptionNumber": 0,
    "paymentOptionNumber": 2,
    "lastChange": "2022-08-19T14:43:07.8438269",
    "isDeleted": false
  },
  {
    "currencyNumber": "EUR",
    "countryNumber": "B",
    "isActive": true,
    "isEDI": false,
    "bankCode": 0,
    "email": "info@aliceetmaman.be",
    "fax": "",
    "id": "cd53f41b-950a-b888-b414-e645209d4761",
    "website": "www.aliceetmaman.be",
    "iban": "",
    "info1": "C\u00e9line Lietaer \nTel: +32 472 96 77 80\n E-mail: celine@aliceetmaman.be",
    "info2": "",
    "bankAccount": "",
    "searchTerm": "ALICE ET MAMAN BVBA",
    "mobilePhone": "",
    "name1": "ALICE ET MAMAN BVBA",
    "name2": "",
    "name3": "",
    "number": 10130,
    "city": "7711 Dottenijs/Dottignies",
    "zipCode": "7711",
    "street": "Z.I. Barri\u00e8re de Fer - Av. Du Bois Jacquet 9",
    "bic": "",
    "telephone": "+32 56 65 36 72",
    "shipmentOptionNumber": 0,
    "paymentOptionNumber": 18,
    "lastChange": "2023-09-26T08:42:40.4283463",
    "isDeleted": false
  },
  {
    "currencyNumber": "EUR",
    "countryNumber": "E",
    "isActive": true,
    "isEDI": false,
    "bankCode": 30070010,
    "email": "maria.alvarez@alparatas.com",
    "fax": "0034-914009218",
    "id": "09162af0-91ce-4348-a32d-d524ee83a43e",
    "website": "www.havaianas.com",
    "iban": "",
    "info1": "",
    "info2": "",
    "bankAccount": "415507300",
    "searchTerm": "Alpargatas Euro",
    "mobilePhone": "",
    "name1": "Alpargatas Europe S.L.U.",
    "name2": "Havaianas",
    "name3": "",
    "number": 10140,
    "city": "Madrid, Espana",
    "zipCode": "E-28042",
    "street": "Av.Arroyo del Santo, 4 bis",
    "bic": "",
    "telephone": "0034-911332672",
    "shipmentOptionNumber": 0,
    "paymentOptionNumber": 2,
    "lastChange": "2022-08-19T14:43:07.8438269",
    "isDeleted": false
  },
  {
    "currencyNumber": "EUR",
    "countryNumber": "D",
    "isActive": true,
    "isEDI": false,
    "bankCode": 0,
    "email": "alpenwahn@logo-schmuck.de",
    "fax": "08024/8668",
    "id": "8710779e-d3b3-4342-9cde-6c77730dde3a",
    "website": "",
    "iban": "",
    "info1": "",
    "info2": "",
    "bankAccount": "",
    "searchTerm": "Alpenwahn GmbH",
    "mobilePhone": "",
    "name1": "Alpenwahn GmbH",
    "name2": "",
    "name3": "",
    "number": 10150,
    "city": "Holzkirchen",
    "zipCode": "83607",
    "street": "Heignkam 4",
    "bic": "",
    "telephone": "08024/3504",
    "shipmentOptionNumber": 0,
    "paymentOptionNumber": 1,
    "lastChange": "2022-08-19T14:43:07.8438269",
